### ISSUE TITLE
Is there a trick to directly use lines such as `#define SIGUSR2 12`?

### ISSUE THREAD

**Issue by grepsuzette** [snowkit/linc_empty#1]
Hi.
Linc is amazing! 
I used it already to create linc_syslog (https://github.com/emugel/linc_syslog) and I now wish to create linc_signal to manage POSIX signals (for instance to intercept or ignore system signals).

When creating `linc_syslog` I merely ended up creating @:enum abstract (Int) and manually copied lines like `#define SOMETHING 35`. But the signals values defined in `<signal.h>` I think manually copying those to an abstract is more dangerous as it's very likely to change from one platform to another.

Do you know if there is a way to work with those #define? (If so, a short example is welcome, because I already tried, writing some C, and failed =)

**Comment by dazKind** [comment]
You should be able to expose the native defines the following way:
```haxe
// Signals.hx
@:include('signal.h')
extern class Signals {
    @:native("SIGABRT")
    public static var Abort:Int;
    //...
}
```
and just use them normally:
```haxe
trace(Signals.Abort); // prints "22" on windows 10
```

**Comment by grepsuzette** [comment]
Perfect, thanks!
