### ISSUE TITLE
How to pass callbacks?

### ISSUE THREAD

**Issue by grepsuzette** [snowkit/linc_empty#2]
Let a **C** function expect a `void (*cb)(int)` parameter.
Is it possible to pass a `Int->Void` from **Haxe** for that parameter, that could be called at a later time by the system? If so, how?

**Comment by haxiomic** [comment]
If the callback is a static function in Haxe then you can use `cpp.Function.fromStaticFunction(haxeCallback);`.

To use non-static functions you can use a wrapper that has a static function which dispatches the non-statics

Here’s and example for GLFW callbacks where we add a wrapper
https://github.com/haxiomic/linc_glfw/blob/892892fa712d02f1147574e484f9134a4fe30319/glfw/GLFW.hx#L235

**Comment by dazKind** [comment]
+**edit**+ Hah, @haxiomic beat me to it. Guess I type too slow :)

---
I'm afraid there is no direct way I know of. 

But what you can do is introduce a simple glue-layer that allows interop via static functions and members. The following pseudo-code should get you started:

```haxe
package sample;

@:nativeGen // Important! generate a pure Cpp-Class for this class.
@:include('signal.h')
@:cppFileCode('
    void cbInit() {
        signal(SIGABRT, sample::NativeSignalInterface::onSIGABRT);
        //...
    };
')
class NativeSignalInterface {
    public static function init():Void {
        untyped __cpp__('cbInit()'):
    }
    public static function onSIGABRT(_signum:Int):Void {
        // forward using some Signaling mechanism
        Signals.onAbort.dispatch(_signum);
    }
    // ...
}

class Signals {
    public static var onAbort:msignal.Signal1<Int>; // using msignal lib as an example here
    //...

    public static function init() {
        NativeSignalInterface.init();
        onAbort = new msignal.Signal1();
        //...
    }
}
```

With that in place you can setup everything in your program and react to the callbacks like so:
```haxe
import sample.Signals;

//... somewhere in your program ...

Signals.init();

function myHaxeHandler(_signum:Int) {
    trace('Caught signal $_signum.');
}

Signals.onAbort.add(myHaxeHandler);
```
I dont have time to compile and test this right now so hopefully it kinda makes sense. 
Lemme know if you need more directions.

**Comment by grepsuzette** [comment]
Thanks a lot.
I ended up using a little bit of both ideas:
```haxe
@:keep
@:include('linc_signal.h')
class SystemSignal {
    private static var _map = new Map<Int, Int->Void >();
    public static function ignore(signum:SigNum) : Void { ExternSignal._ignore(signum); } 
    public static function reset(signum:SigNum) : Void { 
        _map.remove(signum);
        ExternSignal._reset(signum); 
    }
    public static function on(signum:SigNum, cb:SigNum->Void) : Void {
        _map.set(signum, cb);
        ExternSignal._on( signum, cpp.Function.fromStaticFunction(_onsignal) );
    }
    static function _onsignal(n:Int) : Void {   if (_map.exists(n)) _map[n](n); }
}
```
If you're curious, a first working version of the lib is here https://github.com/emugel/linc_systemsignal . 

Feel free to list this in the examples of Linc, as I would like to help push the visibility of this initiative (the more of us there are, the more powerful Haxe will be on Linux).

**Comment by ruby0x1** [comment]
I've been meaning to setup an easier to edit page for this so that contributions can just be added with low friction. thanks for the work on these libraries everyone.
